# Generated by Django 5.1.2 on 2024-10-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='insira o nome', max_length=50)),
                ('cpf', models.CharField(help_text='apenas número', max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('cargo', models.CharField(max_length=20)),
                ('meta', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'funcionario',
                'verbose_name_plural': 'funcionarios',
            },
        ),
    ]
